version: "3"
services:
  museria:
    container_name: museria
    image: metasound/museria
    restart: on-failure
    env_file:
      ./.env
    environment:
      MUSERIA_FACE: $MUSERIA_FACE
      MUSERIA_HOSTNAME: $MUSERIA_HOSTNAME
      MUSERIA_PORT: $MUSERIA_PORT
      MUSERIA_PUBLIC_PORT: $MUSERIA_PUBLIC_PORT 
      MUSERIA_COLLECTION_MUSIC_LIMIT: $MUSERIA_COLLECTION_MUSIC_LIMIT
      MUSERIA_INITIAL_NETWORK_ADDRESS: $MUSERIA_INITIAL_NETWORK_ADDRESS
      MUSERIA_LOGGER_LEVEL: $MUSERIA_LOGGER_LEVEL
      MUSERIA_STORAGE_PATH: $MUSERIA_STORAGE_PATH
      MUSERIA_STORAGE_DATA_SIZE: $MUSERIA_STORAGE_DATA_SIZE
      MUSERIA_STORAGE_TEMP_SIZE: $MUSERIA_STORAGE_TEMP_SIZE 
    ports:
      - $MUSERIA_DOCKER_PORT:$MUSERIA_PORT
    volumes:
      - $MUSERIA_STORAGE_PATH:/usr/src/app/museria